name: Sync and Ivalidation Frontend

on:
  push:
      branches:
          - main 
      paths:
          - frontend/**

jobs:
    sync-frontend:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ vars.AWS_REGION }}
    
          - name: Sync frontend templates with S3
            run: |
              aws s3 sync ./frontend/templates s3://frontent-static-bucket --delete
          - name: Sync config file with S3
            run: |
              aws s3 cp ./frontend/config.json s3://frontent-static-bucket/config.json
          - name: Invalidate CloudFront cache
            run: |
              aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"